name: Backup new release of Tixati

on:
  schedule:
    - cron: '0 7 * * *'
  push:
    paths:
      - .github/workflows/backup-new-release.yml
      - scripts/backup.sh

jobs:
  backup:
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: ./scripts
    steps:
      -
        name: Checkout
        uses: actions/checkout@v7
      -
        name: Backup Tixati installers to FTP
        run: ./backup.sh
        env:
          AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
          AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          S3_ENDPOINT: ${{ secrets.S3_ENDPOINT }}
          S3_BUCKET: ${{ secrets.S3_BUCKET }}
